AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: Stage to deploy resources to
    Default: staging
    AllowedValues:
      - staging
      - production
  LambdaFun:
    Type: String
    Description: Stage to deploy resources to
    Default: Credlewise-Lambda-Function-SAM-staging
    AllowedValues:
      - Credlewise-Lambda-Function-SAM-staging
      - Credlewise-Lambda-Function-SAM-production
  LambdaHand:
    Type: String
    Description: Stage to deploy resources to
    Default: hellopy_sam.lambda_handler
    AllowedValues:
      - hellopy_sam.lambda_handler
      - hellopy_sam.lambda_handler_new

Globals:
  Function:
    Runtime: python3.8
    Timeout: 30
    Tags:
      project: Cradlewise
      environment: !Ref Stage

Resources:
  CredlewiseLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref LambdaFun
      Handler: !Ref LambdaHand
      CodeUri: aws-sam/python
      Description: Lambda SAM function for Credlewise
      AutoPublishAlias: !Ref Stage
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GatewayEvent:
          Type: Api
          
          Properties:
            Path: /test1
            Method: POST

  Myv1Api: 
       Type: AWS::Serverless::Api
       Properties:
           StageName: !Ref Stage

Outputs:
  ApiGatewayInvokeURL:
    Description: URL to invoke the API Gateway endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/test1"
  CredlewiseLambdaFunction:
    Description: "SAM cradlewise Lambda Function ARN"
    Value: !GetAtt CredlewiseLambdaFunction.Arn
